graph TD
    s1[Difficulty Factor for ACTIONS skills]:::F
    s1 --> q1["actual units (empty for now)"]:::S
    q1 == result in ==> r1([factor amount = 0]):::R

classDef S fill:#607D8B,stroke-width:0px,color:#fff;
classDef F fill:#FF9800,stroke-width:0px,color:#fff;
classDef U fill:#673AB7,color:#fff,stroke-width:0px;
classDef R fill:#8BC34A,stroke-width:0px,color:#fff;
