classDiagram
IFactorsFactoryGameInstance --> NFactorsFactoryClient
NFactorsFactoryClient *-- FactorStackArray
FactorStackArray <|.. FactorStask1
FactorStackArray <|.. FactorStask2
FactorStackArray <|.. FactorStask3
FactorStackArray <|.. FactorStask4
FactorStackArray <|.. FactorStask5

class FactorStask1 {
    &lt;&lt;For Action&gt;&gt;
}
class FactorStask2 {
    &lt;&lt;For Dialog&gt;&gt;
}
class FactorStask3 {
    &lt;&lt;For Alignment CNV&gt;&gt;
}
class FactorStask4 {
    &lt;&lt;For Alignment CSV&gt;&gt;
}
class FactorStask5 {
    &lt;&lt;For Alignment NEUTRAL&gt;&gt;
}

class IFactorsFactoryGameInstance {
    &lt;&lt;interface&gt;&gt;  &lt;&lt;public&gt;&gt;
    +GetFactorsFactoryClient() NPointSystemClient
}

class NFactorsFactoryClient {
    &lt;&lt;public&gt;&gt;
    +CreateStack(FString StackName) void
    +GetFactor(TArray&lt;FString&gt; StackNames) TArray&lt;FactorState&gt;
    +AddFactor(TArray&lt;FString&gt; StackNames, Factor) void
}
